name: mojol
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_database: ^9.1.2
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  iconly: ^1.0.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
